version: "3.8"
services:
  db:
    build: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test

  app:
    build: app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./.env:/.env
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_volume:
